<a href="https://colab.research.google.com/github/aavinashverma42-dev/Python/blob/main/Day_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Basic ooperation on Numpy

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.stack((arr1, arr2), axis=1)
print(arr3)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
arr1 +arr2


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


array([5, 7, 9])

In [15]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4
5


In [16]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0:3])
print(arr[1:4])
print(arr[2:5])
print(arr[3:6])

[1 2 3]
[2 3 4]
[3 4 5]
[4 5]


In [23]:
# matrix shaping
arr1 = np.array([1, 2, 3, 4, 5, 6])

np.shape(arr1)
# output format = (no. of rows, no. of columns)

(6,)

In [24]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
m1 = np.array([[1, 2], [4, 5]])
m2 = np.array([[7, 8], [10, 11]])

print(m1 + m2)
m3 = np.dot(m1, m2)
print(m3)


[[ 8 10]
 [14 16]]
[[27 30]
 [78 87]]


In [30]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
np.mean(arr1)

np.float64(3.5)

In [32]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
np.std(arr1)

np.float64(1.707825127659933)

In [37]:
import numpy as np

a = np.random.rand(5)
print(a)

[0.12541373 0.96743591 0.6006349  0.72312984 0.68866417]


In [39]:
import numpy as np

# Create a 2x3 array of random numbers between 0 and 1
multi_dim_array = np.random.rand(2, 3)
print(multi_dim_array)

[[0.42051896 0.11127668 0.8628371 ]
 [0.44410834 0.33017718 0.8170253 ]]


In [47]:
arr6 = np.array([1, 2, 3, np.nan, 5, 6])
print(arr6)

arr7 = np.isnan(arr6)
print(arr7)

arr8 = arr6[~arr7]
print(arr8)

[ 1.  2.  3. nan  5.  6.]
[False False False  True False False]
[1. 2. 3. 5. 6.]


In [ ]:
import time

# Comparison between List and Numpy module
list1 =list(range(1000000000000))
start = time.time()
sum(list1)
end = time.time()
print(end - start)